name: MDC Workflow

on:
  push:
    branchs:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2
      
      - name: Mostrar Mensagem
        run: echo "Olá MDC - my GitHub Actions"
